version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: creditor_db      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres
    networks:
      - api_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - api_network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis      
    ports:
      - "6379:6379"   
    networks:
      - api_network
    restart: unless-stopped

networks:
  api_network:

volumes:
  postgres_data:
  pgadmin_data:
  redis_data: