server:
  port: 5005
  runMode: debug
  domain: localhost
logger:
  filePath: ../logs/
  encoding: json
  level: debug 
cors:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbName: creditor_db
  sslMode: disable  
redis:
  host: localhost
  port: 6379
  password: password
  db: 0  
