server:
  port: 5005 
  runMode: release
  domain: localhost
logger:
  filePath: ../logs/
  encoding: json
  level: debug 
cors:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbName: creditor_db
  sslMode: disable  
redis:
  host: localhost
  port: 6379
  password: password
  db: 0  
password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true